version: '3.4'

services:
  tfg.products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__ProductsDb=${PAYROLL_CONNECTIONSTRING:-Data Source=tfg.products.sqlserver;Initial Catalog=TFG.Products;User ID=sa;Password=Pass@word!;TrustServerCertificate=True}
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - tfg-products-network

  tfg.products.sqlserver:
    user: root
    environment:
      - SA_PASSWORD=${SA_PASSWORD:-Pass@word!}
      - SA_USER=${SA_USER:-sa}
      - ACCEPT_EULA=Y
    ports:
      - "5446:1433"
    volumes:
      - ./config/sql:/var/opt/mssql/data
    networks:
      - tfg-products-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -U $${SA_USER} -P "$${SA_PASSWORD}" -Q "select 1" || exit 1
      interval: 5s
      retries: 3

networks:
  tfg-products-network:
    driver: bridge
    name: tfg-products-network