apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-dply
  labels:
    app: catalog
spec:
  selector:
    matchLabels:
      app: catalog
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: docker.io/wadrydev/tfgproducts
          env:
          - name: ConnectionStrings__ProductsDb
            value: Data Source=host.minikube.internal,5444;Initial Catalog=TFG.Catalog;User ID=sa;Password=Pass@word!;TrustServerCertificate=True
          ports:
            - name: http
              containerPort: 80