apiVersion: v1
kind: Service # Kind of Kubernetes object
metadata:
  name: tfgcatalog-svc # Name of service
spec:
  selector:
    app: catalog # This is the selector that we will use to link to pods
  ports:
  - protocol: TCP # Protocol necessary to access to Service
    port: 80 # Internal Port Number
    targetPort: http # Target port of Container